exec: &exec
  name: build-tools/nerves-system-br
  version: 1.19.0
  elixir: 1.13.4-otp-25

version: 2.1

orbs:
  build-tools: nerves-project/build-tools@dev:0.3.0

workflows:
  build_test_deploy:
    jobs:
      - build-tools/get-br-dependencies:
          exec:
            <<: *exec
          context: org-global
          filters:
            tags:
              only: /.*/
      - build-tools/build-system:
          exec:
            <<: *exec
          resource-class: large
          context: org-global
          requires:
            - build-tools/get-br-dependencies
          filters:
            tags:
              only: /.*/
      - build-tools/build-test:
          exec:
            <<: *exec
          context: org-global
          requires:
            - build-tools/build-system
      - build-tools/install-test:
          hostname: rpi3a._peer.internal
          wg-conf-base64: WIREGUARD_CONF
          context: org-global
          requires:
            - build-tools/build-test
      - build-tools/deploy-system:
          exec:
            <<: *exec
          context: org-global
          requires:
            - build-tools/build-system
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
