exec: &exec
  name: build-tools/nerves-system-br
  version: 1.19.0
  elixir: 1.13.4-otp-25

version: 2.1

orbs:
  build-tools: nerves-project/build-tools@0.2.2

jobs:
  install-test:
    machine:
      image: ubuntu-2204:2022.04.1
    steps:
      - checkout
      - restore_cache:
          key: deploy/test-{{ .Revision }}-{{ .Environment.CIRCLE_TAG }}
      - run:
          name: "System deps"
          command: |
            sudo apt update
            sudo apt install -y wireguard linux-headers-$(uname -r) resolvconf
      - run:
          name: "Save wg0.conf"
          command: |
            sudo echo "$WIREGUARD_CONF" | base64 -d > ~/wg0.conf
      - run:
          name: "Test connection"
          command: |
            sudo wg-quick up ~/wg0.conf
            echo $(dig +short aaa $NODE_NAME)
      - run:
          name: "Push firmware"
          command: |
            cat deploy/test/artifacts/${CIRCLE_SHA1}.fw | ssh -s $NODE_NAME fwup

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build-tools/get-br-dependencies:
          exec:
            <<: *exec
          context: org-global
          filters:
            tags:
              only: /.*/
      - build-tools/build-system:
          exec:
            <<: *exec
          resource-class: large
          context: org-global
          requires:
            - build-tools/get-br-dependencies
          filters:
            tags:
              only: /.*/
      - build-tools/build-test:
          exec:
            <<: *exec
          context: org-global
          requires:
            - build-tools/build-system
      - install-test:
          context: org-global
          requires:
            - build-tools/build-test
      - build-tools/deploy-system:
          exec:
            <<: *exec
          context: org-global
          requires:
            - build-tools/build-system
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
